### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by rupertbulquerin** [ChristianAlexander/FirestoreRestore#1]

**Comment by ChristianAlexander** [comment]
Usage can be found in the README 😀

Pre-built releases are [here](
https://github.com/ChristianAlexander/FirestoreRestore/releases/tag/v0.0.1) or on Docker Hub.

**Comment by ChristianAlexander** [comment]
I think you can also run with the `-h` flag to see the command line flags available.

**Comment by rupertbulquerin** [comment]
Thanks for fast reply!
